### ISSUE TITLE
Control bindings not saved

### ISSUE THREAD

**Issue by Unaccounted4** [deathkiller/jazz2#10]
Using the latest desktop release on Linux (Solus 4, Kernel 4.20, NVidia 418.43, Mono 5.14) the game works and recognizes controller input, however it does not save any custom bindings made in the settings.

The Jazz2.settings file exists but it's garbled if you attempt to open it in UTF8 text format. Interestingly, it seems to save volume settings and scaling option.

**Comment by deathkiller** [comment]
Yes, I know. It does not save controller bindings. I forgot to implement it. I will do it as soon as possible and release new version. ‘Jazz2.settings‘ is not text file, it has custom binary format, so it‘s ok.

**Comment by deathkiller** [comment]
Fixed in v0.5.7.
