### ISSUE TITLE
Improvement: Shorten the duration of the bouncer weapon

### ISSUE THREAD

**Issue by RavenMacDaddy** [deathkiller/jazz2#101]
![image](https://user-images.githubusercontent.com/67732686/183278209-32740363-d2bf-4810-90c7-afed9ca1c987.png)

If the player shoots upwards, they'll keep bouncing for like minutes.

Okay maybe not minutes, but for a very long time - I can empty 99 of them before the first one has disappeared, and sometimes the physics seemingly bugs out so that a bouncer might actually not disappear for minutes, literally.

**Comment by deathkiller** [comment]
This is easy to say, but hard to adjust. I already tried my best to set it as much close as possible.

**Comment by deathkiller** [comment]
It works good in C++ port.
