### ISSUE TITLE
Feature request: Allow the process to be killed by pressing ALT-F4

### ISSUE THREAD

**Issue by RavenMacDaddy** [deathkiller/jazz2#102]
Feature request: Allow the process to be killed by pressing ALT-F4

**Comment by deathkiller** [comment]
I didn't know it doesn't work, but it's probably bug in OpenTK library. It works good in C++ port which uses different library.

**Comment by RavenMacDaddy** [comment]
Found this in a [thread](https://github.com/MonoGame/MonoGame/issues/681) and [PR](https://github.com/MonoGame/MonoGame/pull/872):

```
private void Keyboard_KeyDown(object sender, OpenTK.Input.KeyboardKeyEventArgs e)
        {
            if (e.Key == OpenTK.Input.Key.F4 && (keys.Contains(Keys.LeftAlt) || keys.Contains(Keys.RightAlt)))
            if (e.Key == OpenTK.Input.Key.F4 && keys.Contains(Keys.LeftAlt))
            {
                window.Close();
                return;
```

Would that work?

**Comment by deathkiller** [comment]
Probably yes, but as I said I'm not going to fix it, because it's 3rd party bug, this is only workaround and it's already working in C++ port.

**Comment by RavenMacDaddy** [comment]
Now I get it, C++ version will supersede OpenTK.

**Comment by deathkiller** [comment]
Yes, exactly.

**Comment by RavenMacDaddy** [comment]
Closing as fixed by C++.
