### ISSUE TITLE
Bug: If you shoot while bumping into a ceiling, the projectile will get stopped by it

### ISSUE THREAD

**Issue by RavenMacDaddy** [deathkiller/jazz2#103]
https://user-images.githubusercontent.com/67732686/183481703-b8251e04-b596-4334-9aae-ca65dabec946.mp4

**Comment by deathkiller** [comment]
I can reproduce it in original JJ2 with JJ2+, it works the same.

**Comment by RavenMacDaddy** [comment]
Huh, alright then, must be different tiles - closing.
