### ISSUE TITLE
Possible improvement?: Adjusting tile hitboxes to avoid players getting stuck

### ISSUE THREAD

**Issue by RavenMacDaddy** [deathkiller/jazz2#104]
https://user-images.githubusercontent.com/67732686/183479107-9635175e-41ca-4605-a163-a69efe1228d2.mp4

So this is an example of a tile where they attempted to give it a 3D feel, however that also meant that if the player is too close to get enough speed, they'll just get stuck (and push against thin air).

**Comment by deathkiller** [comment]
I know, but I don't know how to fix it. Some tilesets are poorly designed.
