### ISSUE TITLE
French translation

### ISSUE THREAD

**Issue by Wronschien** [deathkiller/jazz2#105]
Hello, I'm willing to help translating jazz2 into French, but is any real knowledge of the games mandatory ? Because I'm very new to Jazz Jackrabbit, having just bought the games on gog and exploring around a bit. I just find it a pity that there is no French version of this nice project when the original game was translated.

**Comment by deathkiller** [comment]
Hi, it was already translated to French here - https://github.com/deathkiller/jazz2/pull/69 , but I didn't release a new version yet, so it's not included. You can download it separately for now (https://github.com/deathkiller/jazz2/blob/master/Content/i18n/fr.res) and copy it to `Content/i18n/`.

**Comment by Wronschien** [comment]
That's great, thank you
