### ISSUE TITLE
How was this made?

### ISSUE THREAD

**Issue by ArmsOfSorrow** [deathkiller/jazz2#106]
Is there any public docs from reverse engineering the game's code? Or a shared ghidra project or something along those lines?

I'm curious to learn how you approached this :)

**Comment by deathkiller** [comment]
I don't know. I got description of file formats from public sources on the internet and tried to replicate behavior of all objects. I didn't do any reverse engineering.

**Comment by ArmsOfSorrow** [comment]
Makes sense.
I found [this](https://www.jazz2online.com/jcf/showthread.php?t=15059) pretty quickly and I guess there's more to be found.

Thanks for the answer :)
