### ISSUE TITLE
Missing XboxOne UWP port

### ISSUE THREAD

**Issue by Eatmoreapples** [deathkiller/jazz2#107]
I know, its not really an issue. At least for the most, lol. But I dont know how I could get in contact with you otherwise. I just wanted to ask, if you are interested to do a native UWP port of Jazz2 to make Jazz Jackrabbit 2 playable on XboxOne. I am just a member in the Xbox Emulation Hub on discord. Its a very nice and still growing community with round about 30k members which could use some good UWP ports. And I think that could possibly be one of it. If you got time, take a look into the discord server. There are also other developers you could talk to if you have any questions about the Xboxone UWP platform generally. Your work shouldnt be for free, maybe we can open up a bounty if you are interested. It would be nice to see you over there... 

https://discord.com/servers/xbox-emulation-hub-1007582798598647889

**Comment by deathkiller** [comment]
It would be nice to port it to Xbox, but I don't own any Xbox device, so I will not be able to do it myself, but I could help with it. The game uses OpenGL for rendering, which probably is not supported ony Xbox, but Angle library is probably supported there and could be used to automatically translate OpenGL calls to DirectX.

[Also Jazz² Resurrection has Discord too.](https://discord.gg/Y7SBvkD)

**Comment by Eatmoreapples** [comment]
Thank you very much for your quick reply! You are right. Sadly XboxOne UWP is missing OpenGL and Vulcan renderer. Its bound to directx as it seems. Didnt have the original Jazz Jackrabbit 2 game for windows directX already? Anyway. I dont know if your port or that OpenGL version its running with could be even handled via angle to give a good performance in the end (I know that there are some Retroarch cores which use/need angle). I am just a player who enjoys good games. If you can port it over to XboxUWP I would donate my older XboxOneX (it has less power than the newer XboxOne SeriesS/X consoles) and send it to you to get things started if you are interested. Beside the console, you would also need to make a developer account at microsoft and install the devmode on the console itself as far as I can tell. Any suggestions how we could clear up this situation? I could also ask in the server if there is somebody who could take a look and port it over with your source code or how to handle it.

**Comment by deathkiller** [comment]
I think Angle is used by Google Chrome, Edge and some other browsers. Web version of the game already works good in the browser even on mobile phones, so it should be good performance-wise to use Angle library. But I really don't have any experience with it. I think the port should be done by person who has this experience, and I don't have time to learn how to do it, it could take tens of hours with uncertain outcome.

**Comment by Eatmoreapples** [comment]
A little update from me. Got some feedback from a dev in the Xbox Emulation discord who probably has the skills to do it. But wont do it as it seems. He said that a port to UWP would be possible but definitely a pain via angle or transfer to directx. Maybe I open up a bounty someday in the hope that the cash pot gets big enough to be the painkiller for someone that will make a port finally. Or just stick with the windows version. Thank you anyway!

**Comment by deathkiller** [comment]
I just added (partial) support for UWP. It uses special UWP version of Angle. UWP version of OpenAL for sound should be also available, I didn't try it yet. Only input is not implemented yet (which shouldn't be that hard, we can probably use [this](https://learn.microsoft.com/en-us/uwp/api/windows.gaming.input.gamepad?view=winrt-22621)).
Problem is I don't know how to create UWP package yet, so it's also not tested it runs correctly (probably not, because game data paths probably have to be adjusted too). But it seems the most painful part probably is to create runnable UWP package.

**Comment by Eatmoreapples** [comment]
Very nice that you take a look at it. As far as I know for input [Xinput ](https://learn.microsoft.com/en-us/windows/win32/xinput/xinput-game-controller-apis-portal) could be used.

**Comment by tunip3** [comment]
is there a uwp branch, if so I can probably help with some of the path and input stuff.

**Comment by deathkiller** [comment]
Everything is in single branch here - https://github.com/deathkiller/jazz2-native
I added `BuildUwp.bat` to create Visual Studio solution, then you can run the game. You need dependencies and game data though. I can provide it to you on [Discord](https://discord.gg/Y7SBvkD) if you want.

Also it's already running on Windows:
![image](https://user-images.githubusercontent.com/884052/196549317-e4592e11-fdd8-428b-97d5-5e6279a13702.png)

**Comment by deathkiller** [comment]
The game was ported to UWP/Xbox.

**Comment by mediaexplorer74** [comment]
> can probably help with some of the path and input

WOW. You're genius!! Great job, indeed!
