### ISSUE TITLE
Duality: I found some magic architecture at/in this great solution... Wiki needed

### ISSUE THREAD

**Issue by mediaexplorer74** [deathkiller/jazz2#108]
I found some special architecture at/in this great solution... What is Duality? Framework? :) I noticed that this is no Uno... and not Xamarin Forms.... This is your magic... indeed :)
Please create some simple wiki about your multi-platform tech :)
Cheers up,
[m][e]
P.S. I am real man who played the original Jazz Rabbit at 1998 year at IBM PC (x486 and Pentium-1-based)  :)

**Comment by deathkiller** [comment]
C# version which used Duality engine is obsolete now. [New C++ version](https://github.com/deathkiller/jazz2-native) uses modified [nCine](https://ncine.github.io/) engine. Unfortunately, I don't have any additional time to write some wiki articles. Some description how the engine works is out of scope of this project.

**Comment by mediaexplorer74** [comment]
> C# version which used Duality engine is obsolete now. [New C++ version](https://github.com/deathkiller/jazz2-native) uses modified [nCine](https://ncine.github.io/) engine. Unfortunately, I don't have any additional time to write some wiki articles. Some description how the engine works is out of scope of this project.

Ohhhh... I see (I undestand you). Thanx for very quick/fast reply. :) Ok, I 'll google "nCine" and "Duality game engine" :)
