### ISSUE TITLE
No music after level palette changes

### ISSUE THREAD

**Issue by SissiHermanni** [deathkiller/jazz2#109]
Music stops always working when level changes after defeating boss.
Workaround is to exit to menu and reload level.

Game: Jazz2 Secret Files (didn't test Christmas Chronicles)
Versio: 1.1.0

**Comment by deathkiller** [comment]
Level palette is changed every level, it must be something different. I will have to revise audio system.

**Comment by deathkiller** [comment]
It should be fixed now. You can download the latest build in GitHub Actions and test it.

**Comment by deathkiller** [comment]
This should be fixed now too, sorry. You can download the latest build in GitHub Actions and test it.
