### ISSUE TITLE
Enemies multiplying

### ISSUE THREAD

**Issue by SissiHermanni** [deathkiller/jazz2#110]
Jazz2, Episode 2, Level 06, Uterus Boss.

If you die to boss, it multiplies on checkpoint reload. I noticed it when I was going back to the boss are. Crabs where spawning from thin air, and Jazz get random damage from the invisible source. When you get back to boss area, Uterus spawns from different location, but you still get random crab spawn and damage from other invisible Uteruses.

Exit to menu and reload level fixes problem, but it will appear again if you die and let game load checkpoint.

**Comment by deathkiller** [comment]
Both Uterus and spawning of enemies near starting point should be fixed now. You can download the latest build in GitHub Actions and test it.
