### ISSUE TITLE
TNT doesn't break "TNT blocks"

### ISSUE THREAD

**Issue by SissiHermanni** [deathkiller/jazz2#111]
TNT doesn't break "TNT Blocks" 
It works first, but after several destroyed blocks, it stops working.

![Picture1](https://user-images.githubusercontent.com/117662909/201158644-7e7001ff-dc5e-4c28-a046-c94170ffe5cb.png)
![Picture2](https://user-images.githubusercontent.com/117662909/201158650-82f85cac-69a0-459d-8a89-a1a44a4aa1f4.png)
![Picture3](https://user-images.githubusercontent.com/117662909/201158654-8f5a8e7d-ecba-4b20-b6b2-8aad3c1e6fe4.png)

**Comment by deathkiller** [comment]
It should be fixed now. You can download the latest build in GitHub Actions and test it.
