### ISSUE TITLE
Rocks are rolling wrong way

### ISSUE THREAD

**Issue by SissiHermanni** [deathkiller/jazz2#112]
For some reason all rocks are falling and rolling wrong ways.

![Screenshot from 2022-11-11 16-15-19](https://user-images.githubusercontent.com/117662909/201358316-2d3838a3-0379-43b8-95fd-50d6510ee87c.png)
![Screenshot from 2022-11-11 16-16-15](https://user-images.githubusercontent.com/117662909/201358437-39291d7e-796b-4380-be73-9aeae2521d4d.png)

**Comment by deathkiller** [comment]
Should be fixed in https://github.com/deathkiller/jazz2-native/commit/9d9d1a4bb7bbacae805e8d8266d6e40ea33b7154.
