### ISSUE TITLE
(At least some) charging enemies don't know how to charge player

### ISSUE THREAD

**Issue by SissiHermanni** [deathkiller/jazz2#113]
Some charging enemies don't know what they are doing with their lives. 
At least dogs and demons don't know, but fishes, bats, bugs and birds seems to works fine?

https://user-images.githubusercontent.com/117662909/201365049-28ae9c98-dc21-4f4b-a32c-a8a493a3234b.mp4

**Comment by deathkiller** [comment]
I know, it was not fixed yet.

**Comment by deathkiller** [comment]
It should be fixed in commit https://github.com/deathkiller/jazz2-native/commit/80b1dbd6d4f1cc44ba88a59f360a3e00ad885207. Sorry for the delay.
