### ISSUE TITLE
Original Xbox port?

### ISSUE THREAD

**Issue by BevP90** [deathkiller/jazz2#115]
Would an Original Xbox port be possible? I know this is a lot to ask, just wanted an opinion on if you thought the hardware was capable of it. Thank you!

**Comment by deathkiller** [comment]
Sorry, but I'm not interested in porting it to any old console, I don't own them and also I'm targeting to platforms that are people using the most. Question about if it's possible - I don't know, I think the APIs are completely different before UWP was created, so it would have to be rewritten. And also I'm not sure if ANGLE library is supported on older Xbox. If not, then it's would be a lot of work to rewrite all graphics calls from OpenGL to DirectX.
