### ISSUE TITLE
Ammo sprites on map not updated after picking powerup

### ISSUE THREAD

**Issue by Scorcerer** [deathkiller/jazz2#118]
Hi!
Firstly, thank you for a great job! I was playing a lot in my early days, and now nostalgia kicked in hard :)
After spending some time with your implementation (v1.6.0 atm), I noticed that after I pick a gun powerup (for example for flamethrower) the ammo icons on the map stay the same as they were, where in the original game (AFAIR) all sprites were updated (even those on-map to be picked up).

Thank you for this awesome project!

**Comment by deathkiller** [comment]
Hi, this is known limitation, mainly because in splitscreen (which is not implemented yet) both player would share the same ammo sprite, so non-powered up ammo is shown everytime.

**Comment by deathkiller** [comment]
Fixed in commit https://github.com/deathkiller/jazz2-native/commit/9712a77f1d21c9ca70afd26283d9574eca5f1a5a (and splitscreen is not planned for now anyway).
