### ISSUE TITLE
Weapon not reverting to primary state after ammo runs out.

### ISSUE THREAD

**Issue by Scorcerer** [deathkiller/jazz2#119]
Hi!
When you run out of ammunition to an upgraded weapon it should revert to it's non-upgraded version, unless it's a QoL fix?

**Comment by deathkiller** [comment]
Hi, thanks, I didn't know about this, fixed in https://github.com/deathkiller/jazz2-native/commit/bea46c17465358bee751b1a8d59727d40db2d1cc.
