### ISSUE TITLE
Unnecessary loss of health while having a parrot

### ISSUE THREAD

**Issue by Scorcerer** [deathkiller/jazz2#121]
Hi!
I noticed that when you have a parrot and get hit, in addition to losing the parrot you also lose one health. IIRC this wasn't the case in the original - parrot was basically "extra health" that was consumed instead of a normal one.

**Comment by deathkiller** [comment]
Fixed in https://github.com/deathkiller/jazz2-native/commit/9d481266eb7737f0f79c93870797d9b594c5b928.
