### ISSUE TITLE
Frozen boulders not sliding after being pushed

### ISSUE THREAD

**Issue by Scorcerer** [deathkiller/jazz2#122]
Hi!
As in the title, it should be possible for a big rock-like structure (used as a movable platform to reach out to higher places) to be sliding slowly after being frozen by the player. The speed should be the same as when pushing it, but for the reminder of freezing time is should continue to glide unless stopped form the other side.
This would also get around a problem in one problematic place (don't remember where it was now) where the rock is supposed to be pushed on a slope downwards, but it's just the right height the character rather climbs on to it, instead of continuing to push.

**Comment by deathkiller** [comment]
Reworked big boxes/boulders in the latest commit (https://github.com/deathkiller/jazz2-native/commit/c9d715c592ac36db6352586dcef3134f6471a86a) and this should be also fixed.
