### ISSUE TITLE
Problems with font

### ISSUE THREAD

**Issue by Ponywka** [deathkiller/jazz2#124]
Device: Honor 9S
OS: Android 10
Vendor environment: Magic UI 3.1.0.189(C10E3R2P2)
Log: [Jazz2.log](https://github.com/deathkiller/jazz2/files/10608781/Jazz2.log)
J2R Version: [1.6.0](https://github.com/deathkiller/jazz2/releases/tag/1.6.0) (ARMv7)

When I install the game and then open it I got this:
![Screenshot_20230204_164446_jazz2 resurrection](https://user-images.githubusercontent.com/26777464/216771323-d63b5a5d-8734-4bff-9049-aaa10ec15946.jpg)

Also after install [debug build](https://github.com/deathkiller/jazz2-native/actions/runs/4091512930) this problem solved:
![Screenshot_20230204_164144_jazz2 resurrection](https://user-images.githubusercontent.com/26777464/216771411-de9cf028-6e83-4d7f-925e-c678ed7abc8a.jpg)

**Comment by deathkiller** [comment]
Fixed in https://github.com/deathkiller/jazz2-native/commit/7eb948d69027c4b0fa807f76c14363c092db9187. There is some problem with PowerVR GPUs, so some optimization must be disabled. I added your GPU to the list.

**Comment by BombBloke** [comment]
I'm seeing the same issue as pictured by OP. As far as I can tell everything else is working correctly (I'm able to play the actual game), but no text displays.

Device: Google TV Streamer
OS: Android 14
Vendor: Imagination Technologies
Renderer: PowerVR Rogue GE9215
Log: [Jazz2.log](https://github.com/user-attachments/files/25492564/Jazz2.log)
J2R Version: [3.5.0](https://github.com/deathkiller/jazz2/releases/tag/3.5.0) (ARMv7)

**Comment by deathkiller** [comment]
I added also PowerVR Rogue GE9215 to the list. I may have to add all PowerVR GPUs there in the end.
