### ISSUE TITLE
Can't install on Android 

### ISSUE THREAD

**Issue by Noone9852** [deathkiller/jazz2#128]
Hi, I'm trying to install the game on my S23 Ultra but after i grant permission its says i dont have any files in my source folder ( and i really dont). I didnt have any additional files on the ZIP folder with the APKs.

![VideoCapture_20230608-093101](https://github.com/deathkiller/jazz2/assets/135947961/9b091d71-d5d8-4d36-847d-bf72dd060a74)

[Jazz2.log](https://github.com/deathkiller/jazz2/files/11684872/Jazz2.log)

**Comment by deathkiller** [comment]
Hi, you have to put (your own) original Jazz Jackrabbit 2 game files there.
