### ISSUE TITLE
Android version : Screen orientation

### ISSUE THREAD

**Issue by VincentVegaSA** [deathkiller/jazz2#129]
Android port isnt changing screen orientation based on phone native gyro, when I'm using gamepad with fixed phone in it it's upside down.

**Comment by deathkiller** [comment]
It should be fixed in the latest commit https://github.com/deathkiller/jazz2-native/commit/578a58ae61ff090aa4a7cbba29af2bc77b483af6.

**Comment by VincentVegaSA** [comment]
Many thanks. Great work with your Jazz2 ports.
