### ISSUE TITLE
Stuck at teleporter

### ISSUE THREAD

**Issue by sc0ty** [deathkiller/jazz2#130]
In level Flashback I get stuck when I get teleported here.
Game from GOG, with Secret Files.

![image](https://github.com/deathkiller/jazz2/assets/1812478/bfebe58f-5802-478d-afbb-d5a6b4f4a521)

**Comment by sc0ty** [comment]
Here is how I got there
https://youtu.be/pxyOrPqMkfg?t=105

**Comment by deathkiller** [comment]
Sorry, it should be fixed in https://github.com/deathkiller/jazz2-native/commit/0845cadb3cdd8cafe8fc0714f5295cd8532df29b and hopefully didn't break anything else.
