### ISSUE TITLE
Jazz on Android crashes when character morphs

### ISSUE THREAD

**Issue by maxstrike88** [deathkiller/jazz2#133]
Hello.  I was testing the latest experimental version of Android and I found a problem when the character exchanges for another, either due to the morph switch or the witch that turns the character into a frog, the game crashes.

I attach what I got from logcat and the jazz log. This corresponds to the third level of the Shareware Demo episode:

[crashlog.txt](https://github.com/deathkiller/jazz2/files/13302538/crashlog.txt)
[20231108212420_Jazz2.log](https://github.com/deathkiller/jazz2/files/13302542/20231108212420_Jazz2.log)

I hope it helps.

**Comment by deathkiller** [comment]
I see you are using version `2.1.r502-c964c7d`, not the latest one. This bug has been already fixed in version `2.2.1` released yesterday.
