### ISSUE TITLE
2.5.0 BUG: left-aligned intro with option to keep aspect ratio for cutscenes

### ISSUE THREAD

**Issue by Hexaae** [deathkiller/jazz2#136]
As the title says, if you use "keep aspect ratio" option for cutscenes, intro movie will be left align, instead of centered (very ugly to see).

**Comment by deathkiller** [comment]
Fixed in commit https://github.com/deathkiller/jazz2-native/commit/59c3b1c4456ee5a9cd6564219d7a88577e05c639.
