### ISSUE TITLE
Cannot Get Past Arrow Sign in Fourteen Carrot Level

### ISSUE THREAD

**Issue by g1t3m** [deathkiller/jazz2#137]
Platform: Steam Deck
Operating System: SteamOS
Compatibility Layer: None
Version of Jazz Jackrabbit 2 used: JAZZ JACKRABBIT 2 THE SECRET FILES V1.24HF
Version of Jazz 2 Resurrection: 2.5.0
Episode: 3 (Flashback)
Level: Fourteen Carrot

Issue: When playing the Fourteen Carrot Level, I cannot get past the blue arrow sign pointing to the left, as if it's a wall or object instead of a normal direction sign. This is impeding my progress and I am unable to progress further into the level/game as a result. What would be the solution to fixing this glitch so I can continue to play the game?

Thank you for your continued effort of bringing Jazz Jackrabbit to modern, open source consoles!

![ksnip_20240205-154411](https://github.com/deathkiller/jazz2/assets/58442774/5a22af98-97c4-4bf4-83b5-1d097586c518)

**Comment by deathkiller** [comment]
Hi, the wind looks probably too strong, but you should be able to run through it without any issues. Did you try to press Run button?

**Comment by g1t3m** [comment]
What button would be the dedicated Run button on a controller? Assuming I didn't reconfigure the controls from the default settings?

**Comment by deathkiller** [comment]
Probably B button.
