### ISSUE TITLE
Website is down including the wasm implementation

### ISSUE THREAD

**Issue by schumannd** [deathkiller/jazz2#138]
Is there a way to host it myself? The OS-specific way to run it doesn't work (crashes on launch without error)

**Comment by deathkiller** [comment]
Sure, you can build it and host it anywhere you want. I have some issues with the domain, I probably have to get a new one somewhere, then it starts to work again.

> The OS-specific way to run it doesn't work (crashes on launch without error)

That's strange. I haven't got any report that something doesn't work. I just fixed one bug right now though.

**Comment by deathkiller** [comment]
Closed due to inactivity. Feel free to re-open if you have some other questions.
