### ISSUE TITLE
Can't launch: `/usr/bin/jazz2: line 26: /home/jared/.local/share/Jazz² Resurrection/Update/jazz2: No such file or directory` (The directory exists)

### ISSUE THREAD

**Issue by ipaqmaster** [deathkiller/jazz2#140]
Can't launch: `/usr/bin/jazz2: line 26: /home/jared/.local/share/Jazz² Resurrection/Update/jazz2: No such file or directory` (The directory exists)

The shell also returns that it exists with `mkdir` but fails to `ls` it also believing it doesn't exist.

I have a suspicion this is caused by the `mornalization=formD` ZFS property on my /home dataset trying to 'collapse' special characters like this. But I cannot be sure.

I tried this a few years ago as well and ran into the same problem at the time. I have never been able to launch this reimplementation and would like to.

**Comment by deathkiller** [comment]
`/home/jared/.local/share/Jazz² Resurrection/Update/jazz2` - where did this path come from? What source/package are you using? `Update` is not part of source code. You should be able to run the game (the binary) from any directory.

**Comment by ipaqmaster** [comment]
Looks like its packaged here: https://aur.archlinux.org/packages/jazz2-bin. Maybe its doing its own thing?

**Comment by ipaqmaster** [comment]
Seems to work perfectly fine using your latest release tag. I'll stick with this. Thanks!

**Comment by deathkiller** [comment]
Great! AUR package is unofficial and it seems it doesn't have any maintainer now, so I'm not sure what to do with it.
