### ISSUE TITLE
2.9 version crashes

### ISSUE THREAD

**Issue by petran79** [deathkiller/jazz2#143]
Version 2.8 works fine but 2.9 refuses to launch with all exe versions.
I use Windows 10 latest, Nvidia gtx 1080 and i7 4790k

here is crash dump
[Jazz2 (24-10-22-20-43-19).dmp](https://github.com/user-attachments/files/17480208/Jazz2.24-10-22-20-43-19.dmp)

**Comment by deathkiller** [comment]
Ah, I used x86 instruction supported only since Skylake and I didn't know about it, so it crashed on older processors. It should be fine now in the latest experimental build.
