### ISSUE TITLE
No sound in helicopter mode

### ISSUE THREAD

**Issue by NerosTie** [deathkiller/jazz2#16]
Everything works fine with the last release but I have no sound in helicopter mode with Jazz and Lori. Plus, it should have a sound when Spaz start running, but it's not here.

I'm on Linux.

edit: no sound when a bomb explodes

**Comment by deathkiller** [comment]
Yes, I know. Some sound effects are still missing. I didn't have time to fix it yet.

**Comment by deathkiller** [comment]
Copter sound is fixed in **v0.6.1**.

**Comment by NerosTie** [comment]
Cool! Thanks!
