### ISSUE TITLE
When a level is completed, the game crashes

### ISSUE THREAD

**Issue by NerosTie** [deathkiller/jazz2#17]
As the title says, when a level is completed, the game crashes.

[crash.txt](https://github.com/deathkiller/jazz2/files/3364808/crash.txt)

Look at the attached text file, this is what I have when it crashes.

I'm on Linux.

edit: It doesn't crash with 0.5.9, so it's definitively an issue with 0.6.

**Comment by deathkiller** [comment]
Thanks for report. You are right. I fixed it and reuploaded as version 0.6.0, so please download it again.

**Comment by NerosTie** [comment]
It works! (tested with "Formerly a Prince"). Thanks! :+1:
