### ISSUE TITLE
WebGL.NET NuGet

### ISSUE THREAD

**Issue by MarcosCobena** [deathkiller/jazz2#18]
Hey guys,

Good work! Just wanted to let you know can depend on the preview NuGet WebGLDotNET instead of having a local copy of the source code, and enjoy all the fixes we've been doing lately:

https://github.com/WaveEngine/WebGL.NET#webglnet

Please don't hesitate to report bugs or whatever you may find.

Thanks!

—Marcos

**Comment by deathkiller** [comment]
Hi,

thank you. I will use NuGet in further versions. The WebAssembly port of the game is unfortunately only (slow) tech demo right now, but I hope it will run better.
Also, thank you for WebGLDotNet library, it works great!

**Comment by MarcosCobena** [comment]
Thanks! We're interested in the performance issue if you see our library is the one causing the slowness :-)

Thanks again.

**Comment by deathkiller** [comment]
I think the slowness is caused by Mono Runtime itself. I should try to enable AOT compilation somehow, but I don't know how well it works so far.

**Comment by MarcosCobena** [comment]
If your copy of WebGL.NET is older than 1 month or so I'd encourage to give a try with the NuGet one, because we worked on the performance side a little bit. However, yes, maybe AOT will help you guys too. You may be able to profile it with browsers' developers tool.

**Comment by deathkiller** [comment]
I just tried latest version of WebGL.NET and unfortunately it's the same. Mono is probably too slow, but I didn't tried latest Mono yet.

**Comment by MarcosCobena** [comment]
Hmmm ok; yesterday I was updating Mono's NuGets (0.2.0 everything) in the repo but didn't still publish a new version. You can do that too, just in case.

**Comment by MarcosCobena** [comment]
Here you can find them:

https://github.com/WaveEngine/WebGL.NET/tree/master/src/packages

**Comment by MarcosCobena** [comment]
https://www.nuget.org/packages/WebGLDotNET/1.3.0-preview

;-)

**Comment by deathkiller** [comment]
Thank you very much, but it's still slow, I don't know why. Probably nothing can be done about it now.

**Comment by MarcosCobena** [comment]
Hey guys, I've just played again and it works muuuch more faster, what did you change for that? Good job!

**Comment by deathkiller** [comment]
Hi, thanks! I removed some features which were not critical and updated Mono to latest version. It's more playable now, but it's still 10x slower than PC/Android version.
