### ISSUE TITLE
Controller support in Android

### ISSUE THREAD

**Issue by ambrus95** [deathkiller/jazz2#19]
The game only partially supports my Xbox One controller connected via Bluetooth to my phone. The Dpad, triggers, LB, RB, A, B, X and Y don't work.

**Comment by deathkiller** [comment]
Yes, I know. Better gamepad support will be included hopefully in next version. Some changes are already implemented in last commits.

**Comment by deathkiller** [comment]
Fixed in latest commit 3f2fea01835e3cf5a07c2a29620089e27a50979b. Gamepads work as expected now.

**Comment by ambrus95** [comment]
Thanks for addressing it, looking forward to the next release :)
