### ISSUE TITLE
Force close in android 7.1.2

### ISSUE THREAD

**Issue by dhanial** [deathkiller/jazz2#2]
![screenshot_20180513-163519](https://user-images.githubusercontent.com/37980131/39965890-68fa8f22-5691-11e8-877c-c8355bfb757d.png)

**Comment by deathkiller** [comment]
It seems that the game can't find/load font, but I can't reproduce this exception. Please, make sure you followed the installation instructions. You can try to run Windows/Linux/macOS version first.

**Comment by dhanial** [comment]
Ok i'll tried
