### ISSUE TITLE
Customizing touch button position

### ISSUE THREAD

**Issue by dhanial** [deathkiller/jazz2#20]
Please add customizing touch button position for the next update

**Comment by deathkiller** [comment]
Position of touch buttons can be already customized using `Left Controls Padding` and `Right Controls Padding` options. Do you need something more?

**Comment by dhanial** [comment]
I'm can't finding that option

**Comment by dhanial** [comment]
You mean in the option menu ?

**Comment by deathkiller** [comment]
Yes, it must be there in Android version.

**Comment by dhanial** [comment]
I mean freedoom to customizing button position for example (sorry) ppsspp
button position, i can manage position of L and R trigger in the bottom
center or upper corner

**Comment by deathkiller** [comment]
Unfortunately, such feature will probably not be implemented. There is a lot of other issues that should be fixed first. I think current touch button positions are not so bad.

**Comment by dhanial** [comment]
Oh ok it's just my suggest, i still comfortable with default button position
