### ISSUE TITLE
Stomping to spawn hidden gems not working in shareware demo level

### ISSUE THREAD

**Issue by Kreeblah** [deathkiller/jazz2#21]
<img width="717" alt="Screen Shot 2019-09-30 at 16 14 23" src="https://user-images.githubusercontent.com/1812790/65923708-ba36c400-e39e-11e9-9eec-6c7fff3be0f9.png">

In this area in the first level of the shareware demo, you're supposed to be able to stomp between those two light posts in order to spawn some gems.  That doesn't seem to be working (stomping doesn't seem to do anything), at least in my environment.  I'm running 0.6.0 with Mono 5.16.0.221 on macOS 10.14.6, in case that makes a difference.

**Comment by deathkiller** [comment]
I know, hidden gems are not implemented yet. It had lower priority.

**Comment by deathkiller** [comment]
Fixed in **v0.6.1**.
