### ISSUE TITLE
[Feature Request] Write settings and saves to user's HOME

### ISSUE THREAD

**Issue by chewi** [deathkiller/jazz2#23]
Although this has long been standard on Linux, even Windows applications tend to do this now. If this is added then I can finish packaging the game for Gentoo Linux. I already have the package building from source! I would do the work myself but I have enough languages to deal with without adding C# to the list. :stuck_out_tongue:

**Comment by deathkiller** [comment]
Ok, it will be added in next version 🙂 Do you have any idea about filepath? "~/Jazz2.settings"?
Local settings file will still be supported if exists.

**Comment by chewi** [comment]
[This post](https://unix.stackexchange.com/a/313001/161445) explains it pretty well. The standard doesn't seem to define exactly what counts as config or data but I think the former is supposed to be human readable and editable configuration. Bit.Trip Runner2 is a good example that backs this up. `~/.config/gaijin_games/runner2` contains `game.cfg`, which is a plain text .ini-style file. `~/.local/share/gaijin_games/runner2` contains `log.txt`, `runner2.sav`, and `scores.dat`. The first is plain text but not configuration while the other two are binary files. `Jazz2.settings` is binary so I would put it in `~/.local/share/Jazz2/Jazz2.settings`.

**Comment by deathkiller** [comment]
Done (in `multiplayer` branch which will be merged soon anyway).
Default path is `%appdata%\Jazz2\Jazz2.settings` and `%appdata%\Jazz2\Jazz2.log`. To enable portable mode (to work as before) create (empty) `.\Jazz2.settings` file and it will use it automatically. Tested only on Windows, should work on Linux too.

**Comment by chewi** [comment]
It works great, thank you! I'll finish packaging the game soon.
