### ISSUE TITLE
Add FallShootToFall and LedgeClimb to source?

### ISSUE THREAD

**Issue by chewi** [deathkiller/jazz2#30]
Thanks for the release, I've been waiting for it! I'm on the verge of getting this added to Gentoo now but there's just one thing I forgot to address before. In #27, you explained that `FallShootToFall` and `LedgeClimb` are in the released `Main.dz` because they are sometimes missing from the data files. That's fine but if you're building from source, you have to download the release zip just for that. Would you be able to include `Main.dz` in the source tarball or better still, include the original image files so that they get picked up by the import tool? I don't need a new release for this as I can download straight from GitHub in the meantime.

**Comment by deathkiller** [comment]
Done! I also updated versions and translations. I wanted to rename some resources, but I can do it later.
