### ISSUE TITLE
Analog input in menus?

### ISSUE THREAD

**Issue by TrollDecker** [deathkiller/jazz2#32]
Heyo,

Currently, as of the latest release, analog inputs seem to be supported ingame but not in menus, which probably doesn't seem like a big deal for a game like Jazz 2, but it actually presents a couple of problems.

For one thing, on controllers like those made by 8BitDo, buttons that would be analog on a regular Xbox controller are digital inputs (Linux at least still treats them as analog inputs, but they can only ever be 0 and 65535 for off and on, respectively). Similarly, on the 8BitDo M30 (modelled on a 6-button Mega Drive controller), the D-Pad is seen by the OS as an analog stick, as are the C and R buttons.

This causes some difficulties in that
1) I can't navigate menus with the M30's D-Pad and
2) I can't remap my controls to something more comfortable for my preferred controller.

**Comment by deathkiller** [comment]
Hi,

Thank you for report. I know about it, it was low priority. I'll try to fix it when I have time.

**Comment by deathkiller** [comment]
Fixed.
