### ISSUE TITLE
Add italian language support please

### ISSUE THREAD

**Issue by Hexaae** [deathkiller/jazz2#33]
I updated Italian translation for Jazz2 The Secret Files: https://www.jazz2online.com/jcf/showpost.php?p=494419&postcount=7
Can you please add Italian language option?

**Comment by deathkiller** [comment]
I can add it, but this game has different common strings that have to be translated too.
See https://github.com/deathkiller/jazz2/blob/master/Content/i18n/en.res.
Could you translate it and send it back, please?

**Comment by Hexaae** [comment]
Ok, will do in next days...

**Comment by deathkiller** [comment]
Closed due to inactivity.

**Comment by Hexaae** [comment]
Sorry! I forgot to upload it...! 
Here is it, updated to latest en.res

[it.res.txt](https://github.com/deathkiller/jazz2/files/6129302/it.res.txt)
Saved as UTF-8 BOM

**Comment by deathkiller** [comment]
Great, thanks.
