### ISSUE TITLE
[Android] "Content files not found"

### ISSUE THREAD

**Issue by danilvalov** [deathkiller/jazz2#35]
I tried to run the app on my Xiaomi Mi6 and on my Xiaomi Mi Box S. I copied game files to the following paths:
- `/storage/emulated/0/Android/data/jazz2.android/Content/Main.dz` (and other content files)
- `/storage/emulated/0/jazz2.android/Content/Main.dz` (and other content files)
I gave storage access to the app.

But I see:
> Content files not found
> Content should be placed in /storage/emulated/0/Android/Data/jazz2.android/Content/...

<img src="https://p13.f2.n0.cdn.getcloudapp.com/items/v1u4x0GR/2020-12-08%2021.44.20.jpg" data-canonical-src="https://p13.f2.n0.cdn.getcloudapp.com/items/v1u4x0GR/2020-12-08%2021.44.20.jpg" width="500" />

<img src="https://p13.f2.n0.cdn.getcloudapp.com/items/04uNOxlx/2020-12-08%2021.44.14.jpg?source=viewer&v=bd58ddc1ed12037db81863986e3a4ec9" data-canonical-src="https://p13.f2.n0.cdn.getcloudapp.com/items/04uNOxlx/2020-12-08%2021.44.14.jpg?source=viewer&v=bd58ddc1ed12037db81863986e3a4ec9" height="500" />

The game works correctly on my Macbook using this library and my Content directory.

What am I doing wrong?

P.S. I also don't see the app in device apps list on the Xiaomi Mi Box S (Settings -> Applications), so I need to reinstall the app every time to open.

**Comment by danilvalov** [comment]
I found a problem.
I copied the name of directory `­jazz2.­android` from the official site, but there is a hidden symbol after the dot:
![image](https://user-images.githubusercontent.com/2463767/101538905-c8bf3900-39ae-11eb-956a-1aeb01cfd8f2.png)

**Comment by MatanelAbayof** [comment]
for this kind of problems I am using "[Copy as plain text](https://chrome.google.com/webstore/detail/copy-as-plain-text/eneajgkmdhmjmloiabgkpkiooaejmlpk)" chrome extension...
