### ISSUE TITLE
0.6.6 release giving false positives on win 10?

### ISSUE THREAD

**Issue by OsaPL** [deathkiller/jazz2#38]
After installing the newest 0.6.6 release on Win 10 (v1903) I get constantly:
![image](https://user-images.githubusercontent.com/2129313/104163022-fc4e1280-53f5-11eb-889e-65e3aa269088.png)
I am almost sure its a false positive, just a heads up for anyone who also gets this.

**Comment by deathkiller** [comment]
Interesting, but Windows Defender on my PC detects nothing and VirusTotal too.
https://www.virustotal.com/gui/file/56d1ee531ffee51672e981c8eccda55a73b0f6dd05c6c1d3355cc4f939de437b/detection
