### ISSUE TITLE
Mod support?

### ISSUE THREAD

**Issue by TheBricktop** [deathkiller/jazz2#40]
I know its pretty early but is there a possibility to add some novelty to the game?
Mountable mods through mono could be possible i think.

**Comment by deathkiller** [comment]
Everything is possible, it's open source, but better modding support with mountable mods is not available yet. New episodes, levels, tilesets and music is already supported. Sprite replacements should not be so difficult to implement, but I'm not sure about some level scripting (new enemies, events and so on). Do you have any ideas?

**Comment by deathkiller** [comment]
Level scripting with AngelScript is implemented in C++ port, so it's moddable and scriptable now.
