### ISSUE TITLE
Importing from GOG version?

### ISSUE THREAD

**Issue by coreybruce** [deathkiller/jazz2#42]
Hey there I have the GOG version installed on my PC and copied the jazz2 files into the game directory wanting to import it but it always defaults to downloading and using the shareware version, how do I change that?

I tried ```mono Import.exe .``` but it said ```No suitable file with assets found!```

I did try and rename the files so they are lower case but that didn't work either.

**Comment by deathkiller** [comment]
You have to keep it in separate folder and import it from there. It's not designed to import it from `.`. Also try to specify path to original `Jazz2.exe` instead, for example `full/path/to/jazz2/Jazz2.exe`. Ensure that folder also contain `Anims.j2a` file.

**Comment by coreybruce** [comment]
Oh I see so I did it wrong, Alright I'll separate them and see how I go and get back to you. Thanks! :)

**Comment by coreybruce** [comment]
I got it, thanks!
