### ISSUE TITLE
Button press to switch weapon doesn't always work

### ISSUE THREAD

**Issue by Hexaae** [deathkiller/jazz2#43]
When I press <switch weapon> button is often ignored and I have to push button 2-3 times to actually switch weapon.
Same thing happens for my XBox One Bluetooth and Hori Fighting Stick Mini devices.
In the control settings panel the assigned button is always working fine on single press.

Win 10, 1070 8GB, i7-8750H, NVidia 432.31

**Comment by Hexaae** [comment]
Just noticed keyboard (SPACE button) has the same issues: switch weapon button works 1/3.

**Comment by deathkiller** [comment]
Weapon can be switched only when player is controllable. Player is not controllable if, for example, is in tube or is hit by enemy. I think that's the case, so it's not bug. Otherwise controls works good for me.

**Comment by Hexaae** [comment]
Interesting: I can reproduce it on 2 different PCs

**Comment by deathkiller** [comment]
Switch weapon button is handled the same way as other buttons. There is no reason why it shouldn't work, so I really don't know...
