### ISSUE TITLE
Remove resource streaming micro-stutters

### ISSUE THREAD

**Issue by Hexaae** [deathkiller/jazz2#44]
Are there plans to remove annoying resource assets streaming micro-stutters on first loading of a new level?

**Comment by deathkiller** [comment]
Duplicate of #34 (created by you already), please don't create duplicate issues. I don't have such plans right now, maybe someone else?

**Comment by Hexaae** [comment]
oops, sorry I forgot about it :)

**Comment by deathkiller** [comment]
Everything is possible, but I'm afraid I don't have time to implement this feature.

**Comment by deathkiller** [comment]
Added preloading of assets on the start of level to prevent micro-stutters in **v0.6.8**. It should fix 90% of micro-stutters, because some assets can't be preloaded.
