### ISSUE TITLE
Hide mouse pointer in full screen + full screen exclusive?

### ISSUE THREAD

**Issue by Hexaae** [deathkiller/jazz2#46]
REQUEST: remove mouse pointer in fullscreen mode and add fullscreen mode exclusive (not sure if current mode is actually Full window borderless)

**Comment by deathkiller** [comment]
Yes, it's borderless fullscreen. Is there any reason why exclusive fullscreen should be added?

**Comment by Hexaae** [comment]
Gives better performance and usually can enable G-Sync with silky smooth rendering perfectly syncing video refresh to frame rendering...

**Comment by deathkiller** [comment]
I know, but do you really need better performance and G-Sync on this 2D game? The game is designed for 60 frames per second and V-Sync enabled. Even 10 years old notebook has enough performance for it. It seems a bit overkill for me. Also, I don't have better display to test G-Sync anyway.

**Comment by deathkiller** [comment]
Fixed. Mouse cursor will be hidden in fullscreen in next version.
Also, tested with G-Sync compatible monitor and the monitor is syncing with the game refresh rate correctly.
