### ISSUE TITLE
Picking up gun power not upgrading fire rate

### ISSUE THREAD

**Issue by MihaiChirculete** [deathkiller/jazz2#47]
Tested environment: Android
Expected: Picking up gun power up would gradually increase fire rate
Actual: Picking up gun power does not gradually increase fire rate

Notes: It would seem track of power ups picked is kept somewhere since after picking a bunch of them you wont pick anymore

**Comment by deathkiller** [comment]
I just tested it and it works, but the effect is maybe not the same as in the original game. Every fast fire power up reduces weapon cooldown by 2 units (frames). Base weapon cooldown is 40 units (frames) and max. count of power ups is limited to 9 (I think it's the same in the original game).
You could try to adjust it yourself here - https://github.com/deathkiller/jazz2/blob/master/Shared/Jazz2.Core/Actors/Player.Weapons.cs#L262

**Comment by MihaiChirculete** [comment]
Hmmm alright, I will do some more testing maybe the issue was caused by something else instead.
I will further investigate this when I'll have some spare time
