### ISSUE TITLE
Flying enemies are too fast

### ISSUE THREAD

**Issue by MihaiChirculete** [deathkiller/jazz2#49]
Tested envrionment: Android

Some flying enemies such as Bees from Diamondus levels, Piranhas from Beach levels, Ghosts from Medivo are way too fast compared to original game enemies.

**Comment by deathkiller** [comment]
Behaviour of each enemy was written by me. I tried to replicate it from the original game, but it's not so easy, so there might be some differences.

**Comment by MihaiChirculete** [comment]
I totally agree, I am not trying to criticize this project in any way. I think it's amazing!

I am just creating these issues to have them like a to-do list so that development is easier and help gradually improving this project 😄

**Comment by deathkiller** [comment]
I know, thank you for your feedback and support.

**Comment by deathkiller** [comment]
Fixed in **v0.6.8**.
