### ISSUE TITLE
Black screen, but not a crash.

### ISSUE THREAD

**Issue by LucasMegaStriker** [deathkiller/jazz2#5]
I did all steps from jazz jackrabbit forums and tried lots of versions. Look, i dont know what is "build solution" the github tutorial said but i follow the way you have said on JJforum. Anyway, my game doesnt crashes necessarily by this black screen but i can't see anything. I can tap the places intended to have buttons and they reflect the menu sounds. I need know what i doing wrong cuz i have a compatible device with OPENGL3.1... Pls. My discord is LucasMegaStriker#8576 if you need/want see the files and screenshots i take. =)

**Comment by LucasMegaStriker** [comment]
![screenshot_20181223-154404](https://user-images.githubusercontent.com/46081692/50387912-96ec3380-06ff-11e9-91f6-1a1d227cb32d.png)

This crash happens sometimes when i start smash insanely my screen hoping for this works.

**Comment by deathkiller** [comment]
These two error messages are strange. It can be caused by corrupted game data or incompatible OpenGL drivers. So I will probably add some logging to Android version to find out what's wrong.
