### ISSUE TITLE
i don't know parameters format

### ISSUE THREAD

**Issue by deathcat739** [deathkiller/jazz2#50]
.\import.exe x:\xxx\xxx？
.\import.exe "x:\xxx\xxx"？

**Comment by deathkiller** [comment]
yes, both are correct, it's standard Windows parameter format

**Comment by deathcat739** [comment]
i'm run it,but useless. import.exe automatic download the demo.

**Comment by deathkiller** [comment]
Try to drag and drop original `Jazz2.exe` on `Import.exe` from Windows Explorer.
