### ISSUE TITLE
Android: System UI is crashing

### ISSUE THREAD

**Issue by vardecab** [deathkiller/jazz2#51]
Context: Android 11, Secret Files version, built on Windows 10 a couple of days ago

Problem: Most of the time System UI is crashing when the game is loading. Same thing happens when minimizing and coming back to the game.

**Comment by deathkiller** [comment]
It's the first issue with System UI crashing. It seems it's bug in your Android OS, because System UI is part of Android. It's very hard to find out why it crashes, so it's unfixable for me.
