### ISSUE TITLE
How to compile/run with .Net 5 on Linux?

### ISSUE THREAD

**Issue by xcom169** [deathkiller/jazz2#54]
Hello!

How to compile/run with .Net 5 on Linux? The desktop.zip only working with Mono, right? 
I need to build the .sln file with dotnet build .. ?

Thanks!

**Comment by deathkiller** [comment]
Hi,
I haven't tried .NET 5 yet. There is `Jazz2.DotNetCore.csproj` for .NET Core 3 in `Jazz2` directory, but it's very long time ago when I tried .NET Core 3, so I don't know. Also, I'm not sure that all used libraries are compatible with .NET 5, but you can try it.

**Comment by deathkiller** [comment]
I created new solution `Jazz2.NET5.sln` with .NET 5.0 projects, so it can be compiled now, but some files are missing and must be copied to output directory manually. It's not recommended to use .NET 5.0 (instead of Mono), because it has lower performance, especially in intro video.

**Comment by xcom169** [comment]
Thank you very much!
