### ISSUE TITLE
Unable to read beyond the end of the stream

### ISSUE THREAD

**Issue by LucasMegaStriker** [deathkiller/jazz2#6]
![screenshot_20181227-025906](https://user-images.githubusercontent.com/46081692/50466365-f2831f00-0994-11e9-8d1f-b2d869625ca2.png)

Any suggestion? Trying...

**Comment by deathkiller** [comment]
This looks like incomplete game data files.

**Comment by LucasMegaStriker** [comment]
Hmm i got a PocoPhone F1 now, i will try again soon. Thanks for reply! :)

Em sáb, 9 de fev de 2019 17:28, Dan R. <notifications@github.com escreveu:

**Comment by deathkiller** [comment]
Ok, thanks for trying it and let me know :)
