### ISSUE TITLE
Option to Save?

### ISSUE THREAD

**Issue by DebeshMishra** [deathkiller/jazz2#71]
I have been trying to play this on android and there is no reliable way to save. The pause menu says "Save & Exit" but there is no option to "continue" from where you left off. The episode selection screen starts from the start.

**Comment by deathkiller** [comment]
It saves state at the beginning of every level. When you continue the episode, everything will be loaded. Unfortunately, it's not possible to save state in the middle of the level. But every level takes only couple of minutes, so I think it's not a big issue.

**Comment by DebeshMishra** [comment]
> It saves state at the beginning of every level. When you continue the episode, everything will be loaded. Unfortunately, it's not possible to save state in the middle of the level. But every level takes only couple of minutes, so I think it's not a big issue.

Yes you are right, it is just a minor setback but it creates complications in regards to that only one person can play the game otherwise if the second person wants to play the game, they would have to overwrite the progress of the first person or play a different episode which isn't related to main story.

**Comment by deathkiller** [comment]
I see, but it's not easy to implement. As a workaround to have different saves for different persons, you can create a copy of Jazz² Resurrection directory and enable portable mode (http://deat.tk/jazz2/help#how-to-enable-portable-mode-in-jazz-resurrection), everything will be saved to game directory then.

**Comment by deathkiller** [comment]
Added automatic saving on each checkpoint and `Continue` to main menu in commit https://github.com/deathkiller/jazz2-native/commit/a32159f69131d6f79e23c8cbb1e6ad3e5d60dc43. Saving current state (not the checkpoint one) is still not supported, but it should work better than before.
