### ISSUE TITLE
Few functionalities missing from original game

### ISSUE THREAD

**Issue by DebeshMishra** [deathkiller/jazz2#72]
Hi, first of all I want to thank the developers for working on this project. It just hits me with nostalgia playing my childhood games on handheld devices. Shame that there isn't an official port.

Since I want this project to be at its best, I want to report some things that were missing in this game from original game. I will only focus on gameplay functionalities as that's the main part.

So far these are the things I found, will update this issue later if I find some more:

- There is no Fastfire mechanic. The fastfire guns do drop occasionally when you kill the enemies but they don't do anything. (They might add to the score but I didn't notice)
- No sugar rush. I spent 4 levels eating all the food which was available and haven't encountered sugar rush even once which makes me think that it is not implemented.

**Comment by deathkiller** [comment]
Thank you! I'm the only developer working on this project.

1. This is strange. Fastfire should be implemented (https://github.com/deathkiller/jazz2/blob/master/Shared/Jazz2.Core/Actors/Player.Weapons.cs#L78).
2. This is also strange. Sugar rush is also implemented (https://github.com/deathkiller/jazz2/blob/master/Shared/Jazz2.Core/Actors/Player.Interactions.cs#L89). Only sugar rush music and rainbow color cycling effects are missing.

**Comment by DebeshMishra** [comment]
quite possible that effects might be working internally but there is no visual indication. Especially in the case of sugar rush because you would rarely want to collide with the enemies intentionally if there is no visual indicator that sugar rush might be active.

also honestly I haven't noticed fastfire taking effect but it might just be the case that i would need to get more of them to notice the effects.

**Comment by deathkiller** [comment]
Sugar rush has visual indication - white player and stars (palette cycling is not implemented, so it can't change color).
![image](https://user-images.githubusercontent.com/884052/165911185-50dc937c-82fe-43d4-bd8a-ce9dab03578d.png)

I think I tested fastfire back then to be accurate, but if it isn't, the easiest is to go and edit the fastfire constants manually, it's open-source. This accuracy testing will take me several hours, which I don't have right now.

**Comment by DebeshMishra** [comment]
Oh that definitely didn't happen with me till now. I will test more and check if it ever happens. So I have never activated sugar rush till now right since my character never turned white with all those stars?

**Comment by deathkiller** [comment]
Yes, it should activate with 100 food collectibles.
