### ISSUE TITLE
Crash on run with Arch32 laptop 

### ISSUE THREAD

**Issue by coreybruce** [deathkiller/jazz2#75]
Hey guys so I wanted to test the game and see if it would work on my old Arch32 laptop, it has all the latest packages but I would get a crash with a error. One bug I resolved by doing this

https://github.com/SFML/SFML/issues/1832

And the here is the logs for the current crash log and the mono crash log.

https://gist.github.com/coreybruce/f131729389a597e8292d8c8d207d9bb4

https://gist.github.com/coreybruce/c7bee76746256d7374bfa80c2a9ff3f8

**Comment by deathkiller** [comment]
Hi, it seems it crashed in OpenGL call. Is OpenGL 2.1 supported there? Maybe you can try OpenGL ES 2.0 backend (which I haven't tested for a while). Unfortunately, I can't provide a fix, because I don't have such a device.

**Comment by coreybruce** [comment]
Hmm I see so it has to do with OpenGL, well this old laptop only has OpenGL 1.4

Could this game get opengl1.x  support? It would be great to have comparability for old PC's sice the game dows run on them.

**Comment by deathkiller** [comment]
OpenGL 2.1 was released in 2006 and OpenGL 1.4 was released in 2002, it's 20 years. I can't support such old technology with its limitations, sorry. The game uses shaders, multiple render targets, non-power of 2 textures and so on, which is not possible there.

**Comment by deathkiller** [comment]
Sorry, but I'm not interested in investing tens of hours to implement OpenGL 1.x backend that I (and probably anyone else) will not use.

**Comment by coreybruce** [comment]
Damn that's a shame, thanks for your time than.
