### ISSUE TITLE
Portable mode?

### ISSUE THREAD

**Issue by enzeinzen** [deathkiller/jazz2#76]
Hi, could you add a command line flag to change the settings / save directory? Or one for a portable mode.
Also, using "²" in that directory's name is bound to break a lot of stuff (portable launchers, etc) so it would be nice if there were a way to change that (via command line).

Thanks

**Comment by deathkiller** [comment]
Portable mode is already implemented, see http://deat.tk/jazz2/help#how-to-enable-portable-mode-in-jazz-resurrection

Not supporting "²" and other unicode characters is not my issue. UTF-8 and UTF-16 encodings should be supported everywhere these days.
