### ISSUE TITLE
Bug: Character doesn't duck after doing Down+Jump or ground pound (player keeps holding Down)

### ISSUE THREAD

**Issue by RavenMacDaddy** [deathkiller/jazz2#78]
Examples:

Spaz does Down+Jump, player keeps holding Down.
Any character does a ground pound, player keeps holding Down.
Lori does Down+Jump, player keeps holding Down.

By the way, just found this project, thank you for your work.

**Comment by deathkiller** [comment]
Thanks, I know about it, but it has very low priority.

**Comment by deathkiller** [comment]
Should be fixed in the latest commit (https://github.com/deathkiller/jazz2-native/commit/fa1829d65274b1377223f561585cae0252f00c14).
