### ISSUE TITLE
About the project

### ISSUE THREAD

**Issue by Askmewho** [deathkiller/jazz2#8]
Great work!!! Could i ask you the actual state of the game?? The are all the mission implemented? Secret files??

**Comment by deathkiller** [comment]
Thank you! The game is almost complete. You can play all levels from JJ2 and The Secret Files. There are still some minor elements missing, like rocks and swinging vines in Jungle and birds, but you can play whole campaign till the end without any issues. And multiplayer is not finished yet.

**Comment by Askmewho** [comment]
Great!!! Ok i will wait to that multiplayer feature because my nieces used to play it on co-op!! They play
my setup with notaz decompiled and recompoiled jazz2 on rpi3 across wine. It works great but lacks of some features than you implementation has. Thank you !

**Comment by Askmewho** [comment]
When yo say multiplayer you are saying local or netplay?? When do you expect to have that feature included?

**Comment by deathkiller** [comment]
Only netplay was planned and I really don't know when it will be ready. There are some other issues that I want to resolve first.

**Comment by xdub** [comment]
Splitscreen would be fine. Maybe someone will implement it in the future. ☺

**Comment by Askmewho** [comment]
please, think about an splitscreen setup. I understand than its more difficult for reasons than i dont know.

**Comment by deathkiller** [comment]
I already thought about it... First I want to add missing minor features and objects and optimize some parts, then I want to implement multiplayer, but I work on it only in my free time, it can take several months.
