### ISSUE TITLE
Improvement: Adjust the hitboxes of enemies to correspond to their respective models

### ISSUE THREAD

**Issue by RavenMacDaddy** [deathkiller/jazz2#80]
Was trying to ground pound the first enemies, the turtles in Castle1, however the hitboxes don't go to the ends of their models as expected (like the original, and what's intuitive to the player), but only right in the middle.

Would be a great improvement to make the hitboxes for the enemies correspond to their respective width and height.

**Comment by deathkiller** [comment]
Player has a narrower hitbox, but enemies should have full-size hitboxes. Anyway, collisions were revised and hopefully this should be fixed.

**Comment by deathkiller** [comment]
It should be fixed in C++ port with reworked collisions.
