### ISSUE TITLE
Bug?: Can't climb faster by using the Run button (seems to work in C++)

### ISSUE THREAD

**Issue by RavenMacDaddy** [deathkiller/jazz2#82]
Currently playing with a controller using Xinput for reference.

I can't climb faster by using the Run button - is this intentional?

**Comment by deathkiller** [comment]
Can you describe it in more detail?

**Comment by RavenMacDaddy** [comment]
Sure, so in the original, whenever you climb, if you hold down the Run button your character will climb faster - this is properly animated as well.

So you can climb with two different speeds:

Normal - Only using directional buttons
Fast - Holding down Run while using the directional buttons

**Comment by deathkiller** [comment]
Ah, I see. It will be fixed.

**Comment by RavenMacDaddy** [comment]
In the web demo I was able to climb faster as intended when I tried.

**Comment by deathkiller** [comment]
Yes, I fixed it a little while ago.
