### ISSUE TITLE
Bug: Duplicate sounds (e.g. when hitting two jump pads at the same time)

### ISSUE THREAD

**Issue by RavenMacDaddy** [deathkiller/jazz2#83]
Dunno if this is unsolvable and more of a limitation of the game, but whatever the case, a good example is if I go down on both of these platforms by aligning myself in the middle:

![image](https://user-images.githubusercontent.com/67732686/183256529-1bd649f0-fdc8-417e-bb52-ebf1e944eb88.png)

Now either that would play the same SFX at the same time, which leads to an uncomfortable volume increase, or it would result in two different SFX playing at the same time, colliding with each other.

**Comment by deathkiller** [comment]
Does it play only one SFX in the original game? I will try to fix it.

**Comment by RavenMacDaddy** [comment]
In fact, in the original I wasn't able to hit both of the pads at the same time even if I tried to reproduce it - it always hit one of them.

Regarding the issue overall, duplicate sounds has always been a limitation of the original, e.g. if you use dynamite and explode a lot of blocks, the game will play the SFX for every block that's destroyed - which obviously becomes very loud.

**Comment by deathkiller** [comment]
Fixed in C++ port. Player can't trigger both springs anymore.
