### ISSUE TITLE
Bug?: Inconsistent ledge grabbing

### ISSUE THREAD

**Issue by RavenMacDaddy** [deathkiller/jazz2#84]
![image](https://user-images.githubusercontent.com/67732686/183256694-6e53ffd2-db6e-4f0d-9a79-ce0caedbfbf1.png)

As illustrated here, a full ledge works, but a smaller one that sticks out doesn't (even though logically they would both be equally as climbable).

Is this to not make the feature too game-breaking, or does it need tweaking?

**Comment by deathkiller** [comment]
This is intentional, only bigger walls can be climbed, to make it less over-powered. It's already very strong sometimes, but player has higher gravity here than in the original game, so it's for balance
