### ISSUE TITLE
Bug?: Unable to double jump with Spaz when jumping from a rope-climb

### ISSUE THREAD

**Issue by RavenMacDaddy** [deathkiller/jazz2#85]
![image](https://user-images.githubusercontent.com/67732686/183257201-257e60bd-c601-44a4-9aa4-7db9c384aa5c.png)

At least in the original, you're able to double jump from a rope-climb - is that intentionally toned down?

**Comment by deathkiller** [comment]
Yes, this is intentional, because I was not able to fix it, so I left it as is.

**Comment by deathkiller** [comment]
Fixed in C++ port.
