### ISSUE TITLE
Bug - Propeller carrot: Unable to move and too short of a duration

### ISSUE THREAD

**Issue by RavenMacDaddy** [deathkiller/jazz2#86]
![image](https://user-images.githubusercontent.com/67732686/183257345-59a852c9-f26e-425b-8a72-c1a64ee7f6bb.png)

While in this state, you just get stuck at the top of whatever ceiling there's.

Screenshot was taken from the original version.

Also, the duration of the powerup is a few seconds, making the intended secret to the right on 1-2 possibly unreachable.

- [ ] Enable movement
- [ ] Increase duration

**Comment by deathkiller** [comment]
Fixed in C++ port.
