### ISSUE TITLE
Bug - First boss: Rocks come down far away from the player

### ISSUE THREAD

**Issue by RavenMacDaddy** [deathkiller/jazz2#87]
![image](https://user-images.githubusercontent.com/67732686/183257488-12afa6fc-e1c2-40c3-9927-10e1d489315f.png)

Yeeeah...paint skills.

Anyway, whenever the boss stomps the ground, a rock never falls where the player is standing (so that they've to actively dodge it), but far away, so the intended challenge is absent.

**Comment by deathkiller** [comment]
It should fall where the player is standing? I use random here, so you never know where it falls.

**Comment by RavenMacDaddy** [comment]
At least the time I played the boss, it never dropped on top of me.

Two things to consider: 

1. What makes the fight/challenge work in the original is the rock dropping on top of you, while she screams at random times, pushing you back.

So you as the player try to dodge the rock, while not knowing whether she'll scream or not, so maybe you overshoot and go into the spikes, or you undershoot and get hit by the rock. 

That's the dynamic of the fight. 

2. Since the distance between the floor and ceiling is relatively short, randomly dropping risk becoming a Sonic situation where it gets too challenging to react and therefore creates frustration for the player.

**Comment by deathkiller** [comment]
I get it, I will try to improve it.

**Comment by deathkiller** [comment]
Fixed in C++ port.
