### ISSUE TITLE
Bug: Noticeable tile-ceiling at the top of the level border

### ISSUE THREAD

**Issue by RavenMacDaddy** [deathkiller/jazz2#88]
![image](https://user-images.githubusercontent.com/67732686/183257788-1ad86a9e-669e-4701-b1af-44a1ccd4a80c.png)

Just checked and this doesn't happen in JJ2+ at least.

JJ2+:

![image](https://user-images.githubusercontent.com/67732686/183258021-86e1f241-28d7-40f5-b4ba-3f9474b63d1f.png)

**Comment by deathkiller** [comment]
This is such minor issue that it will probably not be fixed, but it could be already fixed here - https://github.com/deathkiller/jazz2-native

**Comment by deathkiller** [comment]
Fixed in C++ port.
