### ISSUE TITLE
Unresponsive Touch Controls on Pixel 2 XL

### ISSUE THREAD

**Issue by corrupt3k** [deathkiller/jazz2#9]
First off, love this project. I was super excited to find out I could play Jazz on my phone. Thanks for your hard work! The app itself works great, no issues there.

The only problem I have is that the touch controls are not very responsive. I have to touch the buttons just right or multiple times to get them to trigger. Unfortunately, this makes the game not very fun to play.  :(

**Comment by deathkiller** [comment]
Thank you very much.

Could you specify your problem, please? It's a problem with only D-pad buttons (on the left), action buttons (on the right) or both? Are buttons too small or only their trigger zones are small or misaligned? Can you send me a screenshots (ideally with marked trigger zones) to see what's wrong? Or it's only problem with touching several buttons at the same time?

And the rest of the app works fine? No lags? Music and SFX play?

**Comment by corrupt3k** [comment]
It's all buttons, D-pad and Action. The behavior itself is hard to explain. I can tap the same button repeatedly in the same spot and sometimes it works, sometimes it doesn't. I do seem to get better responses if I tap the buttons "lightly". Like barely touching the screen.
Maybe the trigger zones are too small? I have to touch the direct center of the buttons. anything outside of that does not respond.
![Screenshot_20190314-102606](https://user-images.githubusercontent.com/20589688/54374566-014caa00-4645-11e9-9b55-7a0992eb893b.png)

**Comment by deathkiller** [comment]
Issues with touch controls and music should be fixed in **v0.5.6**. Please, let me know if it works.

**Comment by corrupt3k** [comment]
Controls are working great now! Still no music though.

**Comment by deathkiller** [comment]
That's strange. I will have to look at it again.

**Comment by deathkiller** [comment]
Music playback is fixed in v0.5.7.
