### ISSUE TITLE
Bug - Flying Lizard Goon: Doesn't drop their flight device

### ISSUE THREAD

**Issue by RavenMacDaddy** [deathkiller/jazz2#90]
![image](https://user-images.githubusercontent.com/67732686/183258178-2f1a6e28-84bd-47d1-8c5e-359172dd981f.png)

When these enemies have a flight device, even if I shoot them in the middle of their body, nowhere near the device itself (don't remember if that's a thing or not to be honest...), they never drop from it - the flight device just disappears.

**Comment by deathkiller** [comment]
Fixed in C++ port.
