### ISSUE TITLE
Feature request: Level select

### ISSUE THREAD

**Issue by RavenMacDaddy** [deathkiller/jazz2#92]
Something I miss dearly as I'm testing.

The current operation is pretty slick, however the option to select the level instead would be a great leap forward.

![image](https://user-images.githubusercontent.com/67732686/183258720-1095b7f6-8cff-4d9c-81c1-558fef9afdfe.png)

When loading the game as it's now, the checkpoint that the player was on is not saved - maybe this is harder to implement, but at least the original manual save by definition got around the issue.

**Comment by deathkiller** [comment]
I think this would break the game and make it less difficult. You can already use cheats - http://deat.tk/jazz2/help#how-to-enable-cheats

Manual saving is not supported, because saving state of each object is not implemented and it's really a lot of work.
