### ISSUE TITLE
Improvement: Big volume difference for SFX comparing the main menu to gameplay (low volume in the main menu)

### ISSUE THREAD

**Issue by RavenMacDaddy** [deathkiller/jazz2#94]
I noticed this since I like to hear the soundtrack, so my audio balance is:

Music 100% 
SFX ~50%.

With that, the balance between SFX and music is great, but when on the main menu, it's very noticeable that the SFX, e.g. when going up and down and selecting in the menu, is very low compared to when in a game session.

I suspect the music being muffled when opening the menu during gameplay is the logical design culprit; in-game it becomes fine, but the music isn't muffled when on the main menu, so it becomes too low instead.

To be honest I'm not sure what's the best solution here, cause simply upping the volume for those subjectively obnoxious sounds might not be the most desirable action either - I don't blame you if this is closed as "won't fix".

**Comment by deathkiller** [comment]
Volume of menu SFX is intentionally multiplied by 0.4 (and 0.5 in some cases), so it's not too loud and anoying, but I can adjust it, although you are the first who noticed it.

**Comment by RavenMacDaddy** [comment]
I mean, I respect the decision - the SFX aren't exactly meant to be nice sounding.

**Comment by deathkiller** [comment]
Fixed in C++ port.
