### ISSUE TITLE
Bug: Ground-pounding inside another sprite cancels the animation

### ISSUE THREAD

**Issue by RavenMacDaddy** [deathkiller/jazz2#95]
I mean, it feels awesome, but at the same time not intended - obviously compared to the original - but more importantly, it ruins the risk-reward aspect of the ground-pound where the full animation is the key.

Example here with a downed turtle:

https://user-images.githubusercontent.com/67732686/183481268-209d7e27-0556-44cb-b134-a6d6d25faf7c.mp4

Same thing goes if you manage to ground-pound something while in the air - the key is that the player/character is inside another sprite when the ground-pound is executed.

**Comment by deathkiller** [comment]
I tried it in JJ2 with JJ2+ and it seems it works the same.
