### ISSUE TITLE
Bug: Idle animations are missing the SFX

### ISSUE THREAD

**Issue by RavenMacDaddy** [deathkiller/jazz2#97]
![image](https://user-images.githubusercontent.com/67732686/183259714-1432a7ed-c8cb-4f95-aa2a-6332be659476.png)

**Comment by deathkiller** [comment]
Yes, idle animations are not complete. It has very low priority, because it takes so much time to make it right and has almost no gain.

**Comment by deathkiller** [comment]
Added SFX to some idle animations. Some SFXs are still missing, but I'm postponing it for now.
