### ISSUE TITLE
Bug - Spaz: Risk destroying only one !-block with a flying kick

### ISSUE THREAD

**Issue by RavenMacDaddy** [deathkiller/jazz2#98]
![image](https://user-images.githubusercontent.com/67732686/183259812-9fbfca23-5409-4b46-a2e5-7e5fa0bd0cee.png)

Spaz stopped after the first one was destroyed.

**Comment by deathkiller** [comment]
It works for me, but there are so many problems with the physics that it probably could happen. I will try to fix it.

**Comment by deathkiller** [comment]
It should be fixed in C++ port with reworked collisions.
