### ISSUE TITLE
Improvement: Make it more consistent to get through one block-sized space

### ISSUE THREAD

**Issue by RavenMacDaddy** [deathkiller/jazz2#99]
![image](https://user-images.githubusercontent.com/67732686/183277772-47fa706d-b5a7-48ba-8e04-2c0c1ace4a1d.png)

Like these.

God forbid I shot the lower block, cause then I couldn't be saved by the ledge climb.

**Comment by deathkiller** [comment]
It works for me. What's the problem with this?

https://user-images.githubusercontent.com/884052/183307079-91851544-ffa1-4383-91c1-cc4399f4fe65.mp4

**Comment by RavenMacDaddy** [comment]
https://user-images.githubusercontent.com/67732686/183467215-178420d8-06c4-4e34-8f14-be2e6bbb64fc.mp4

So, this is the discussion at hand...when the player does a full jump, even if they hold the direction button towards the wall the whole time, the character will only get inside the space a little bit every time, but they won't get through it - however:

https://user-images.githubusercontent.com/67732686/183468132-2af7b890-88b0-4f46-aeda-bf674fe1fba1.mp4

So depending on the tile, the player might get through with a full jump or not, which becomes inconsistent.

Yes, obviously you can short jump, and an argument can be made that it's the point and skill of the player to do so - it's the inconsistency with the result that becomes the issue.

**Comment by deathkiller** [comment]
I know, but I think it was floating too much in the original game, so I fixed it like this and this is the result. So it's probably unfixable.
